export const autogeneratedComment = `
// --------------------------------------------------- 
// NOTE: This file is auto-generated by StyleDictionary.
// Any modifications made directly to this file will be 
// overwritten the next time StyleDictionary script runs.
//
// Last updated: ${new Date().toLocaleString()}
// ---------------------------------------------------

`;
