// ---------------------------------------------------
// NOTE: This file is auto-generated by StyleDictionary.
// Any modifications made directly to this file will be
// overwritten the next time StyleDictionary script runs.
//
// Last updated: 3/5/2024, 2:09:19AM
// ---------------------------------------------------

import { base } from './base';

export const semantic = {
  color: {
    bg: {
      strong: base.color.gray70,
      subtle: base.color.gray10,
      default: base.color.white,
      disabled: base.color.gray30,
      brand: base.color.blue50,
      brandDefault: base.color.blue05,
      brandHover: base.color.blue25,
      success: base.color.green15,
      successStrong: base.color.green50,
      error: base.color.red15,
      errorStrong: base.color.red50,
      warningStrong: base.color.yellow50,
      warning: base.color.yellow20,
      info: base.color.sky15,
      infoStrong: base.color.sky50,
      transparent: base.color.transparent,
      active: base.color.gray90,
      logo: base.color.wesparkleRed,
      brandStrong: base.color.blue90,
    },
    content: {
      default: base.color.gray90,
      subtle: base.color.gray80,
      disabled: base.color.gray60,
      knockout: base.color.white,
      brand: base.color.blue50,
      brandSubtle: base.color.blue05,
      brandStrong: base.color.blue70,
      success: base.color.green90,
      successIcon: base.color.green50,
      error: base.color.red90,
      errorIcon: base.color.red50,
      warning: base.color.yellow95,
      warningIcon: base.color.yellow50,
      info: base.color.sky90,
      infoIcon: base.color.sky50,
      link: base.color.blue50,
      linkStrong: base.color.blue90,
      linkSubtle: base.color.gray80,
      linkHover: base.color.blue70,
    },
    border: {
      default: base.color.gray60,
      strong: base.color.gray80,
      disabled: base.color.gray60,
      knockout: base.color.white,
      brand: base.color.blue50,
      brandSubtle: base.color.blue05,
      brandStrong: base.color.blue70,
      success: base.color.green50,
      error: base.color.red50,
      warning: base.color.yellow50,
      info: base.color.sky50,
      transparent: base.color.transparent,
      active: base.color.gray90,
      brandHover: base.color.blue25,
      divider: base.color.gray30,
    },
  },
  border: {
    radius: {
      none: base.border.radius.radius0,
      small: base.border.radius.radius4,
      default: base.border.radius.radius16,
      large: base.border.radius.radius60,
      pill: base.border.radius.radius900,
      round: base.border.radius.radius900,
    },
    width: {
      none: base.border.width.stroke0,
      thin: base.border.width.stroke1,
      default: base.border.width.stroke2,
      medium: base.border.width.stroke4,
      thick: base.border.width.stroke6,
      focus: base.border.width.stroke2,
    },
  },
  spacing: {
    spacing3Xs: base.spacing.spacing4,
    spacing2Xs: base.spacing.spacing8,
    spacingXs: base.spacing.spacing12,
    spacingS: base.spacing.spacing16,
    spacingM: base.spacing.spacing20,
    spacingL: base.spacing.spacing24,
    spacingXl: base.spacing.spacing32,
    spacing2Xl: base.spacing.spacing48,
    spacing3Xl: base.spacing.spacing56,
    spacing4Xl: base.spacing.spacing64,
  },
};
