// ---------------------------------------------------
// NOTE: This file is auto-generated by StyleDictionary.
// Any modifications made directly to this file will be
// overwritten the next time StyleDictionary script runs.
//
// Last updated: 3/5/2024, 2:09:19AM
// ---------------------------------------------------

import { theme } from './theme';

export const semantic = {
  color: {
    bg: {
      strong: theme.color.backgroundStrong,
      subtle: theme.color.backgroundSubtle,
      default: theme.color.background,
      disabled: theme.color.backgroundDisabled,
      brand: theme.color.primary,
      brandDefault: theme.color.primaryLight,
      brandHover: theme.color.primaryHover,
      success: theme.color.successLight,
      successStrong: theme.color.success,
      error: theme.color.errorLight,
      errorStrong: theme.color.error,
      warningStrong: theme.color.warning,
      warning: theme.color.warningLight,
      info: theme.color.infoLight,
      infoStrong: theme.color.info,
      transparent: theme.color.transparent,
      active: theme.color.active,
      logo: theme.color.logo,
      brandStrong: theme.color.primaryStrong,
    },
    content: {
      default: theme.color.text,
      subtle: theme.color.textSubtle,
      disabled: theme.color.textDisabled,
      knockout: theme.color.textInverse,
      brand: theme.color.primary,
      brandSubtle: theme.color.primaryLight,
      brandStrong: theme.color.primaryStrong,
      success: theme.color.successDark,
      successIcon: theme.color.success,
      error: theme.color.errorDark,
      errorIcon: theme.color.error,
      warning: theme.color.warningDark,
      warningIcon: theme.color.warning,
      info: theme.color.infoDark,
      infoIcon: theme.color.info,
      link: theme.color.primary,
      linkStrong: theme.color.primaryStrong,
      linkSubtle: theme.color.textSubtle,
      linkHover: theme.color.primaryHover,
    },
    border: {
      default: theme.color.border,
      strong: theme.color.borderStrong,
      disabled: theme.color.border,
      knockout: theme.color.textInverse,
      brand: theme.color.primary,
      brandSubtle: theme.color.primaryLight,
      brandStrong: theme.color.primaryStrong,
      success: theme.color.success,
      error: theme.color.error,
      warning: theme.color.warning,
      info: theme.color.info,
      transparent: theme.color.transparent,
      active: theme.color.active,
      brandHover: theme.color.primaryHover,
      divider: theme.color.borderSubtle,
    },
  },
  border: {
    radius: {
      none: theme.border.radius.none,
      small: theme.border.radius.small,
      default: theme.border.radius.medium,
      large: theme.border.radius.large,
      pill: theme.border.radius.pill,
      round: theme.border.radius.round,
    },
    width: {
      none: theme.border.width.none,
      thin: theme.border.width.thin,
      default: theme.border.width.regular,
      medium: theme.border.width.medium,
      thick: theme.border.width.thick,
      focus: theme.border.width.focus,
    },
  },
  spacing: {
    spacing3Xs: theme.spacing.xxxs,
    spacing2Xs: theme.spacing.xxs,
    spacingXs: theme.spacing.xs,
    spacingS: theme.spacing.sm,
    spacingM: theme.spacing.md,
    spacingL: theme.spacing.lg,
    spacingXl: theme.spacing.xl,
    spacing2Xl: theme.spacing.xxl,
    spacing3Xl: theme.spacing.xxxl,
    spacing4Xl: theme.spacing.xxxxl,
  },
};
