export const typography = {
  heading: {
    h1: {
      fontSize: 36,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 44,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    h2: {
      fontSize: 28,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 36,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    h3: {
      fontSize: 24,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 34,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    h4: {
      fontSize: 21,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 28,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    h5: {
      fontSize: 16,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 22,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    h6: {
      fontSize: 14,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 1.68,
      lineHeight: 18,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
  },
  body: {
    default: {
      fontSize: 16,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 28,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    small: {
      fontSize: 14,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 22,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    large: {
      fontSize: 20,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 400,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 28,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
  },
  title: {
    large: {
      fontSize: 24,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 32,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    default: {
      fontSize: 20,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 22,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    small: {
      fontSize: 18,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 22,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
  },
  label: {
    default: {
      fontSize: 16,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 22,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    small: {
      fontSize: 14,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 18,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    large: {
      fontSize: 20,
      textDecoration: 'none',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 24,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
  },
  link: {
    large: {
      fontSize: 20,
      textDecoration: 'underline',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 24,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    default: {
      fontSize: 16,
      textDecoration: 'underline',
      fontFamily: 'Montserrat',
      fontWeight: 700,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
    small: {
      fontSize: 14,
      textDecoration: 'underline',
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontStyle: 'normal',
      fontStretch: 'normal',
      letterSpacing: 0,
      lineHeight: 18,
      paragraphIndent: 0,
      paragraphSpacing: 0,
      textCase: 'none',
    },
  },
};
